### ISSUE TITLE
Implementing a Costumised Scoring Function

### ISSUE THREAD

**Issue by guidozuc** [ielab/elastic4IR#3]
1. Describe how to do this functionality in the README.md file. Include code snippets in the description. 
2. Create a small test application that implements this functionality

**Comment by jimmyoentung** [comment]
Please refer to https://github.com/jimmyoentung/ES-KLDivergenceSimilarity which explains step-by-step to implement a customised scoring function: KLDivergenceSimilarity for ElasticSearch 5.1.1
