### ISSUE TITLE
Getting Snippet Text for Query Results

### ISSUE THREAD

**Issue by guidozuc** [ielab/elastic4IR#7]
1. Describe how to do this functionality in the README.md file. Include code snippets in the description. 
2. Create a small test application that implements this functionality

**Comment by AntonQUT** [comment]
Do you want a client-side code snippet - so say (angular) java script?

**Comment by guidozuc** [comment]
that would be nice, Anton.
I suggest listing which endpoints in Elasticsearch's API can be used to get this. And then show an example of how to get this within an app - either python, java, or, as you said, angular

**Comment by guidozuc** [comment]
you can have a look at Harry's commits.
